server:
  port: 8081
spring:
  datasource:
    username: root
    password: '@Hx1234568.'
    url: jdbc:mysql://8.137.82.234/db_homemaking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: user-service