server:
  port: 8081
spring:
  datasource:
    username: root
    password: 2530
    url: jdbc:mysql://localhost:3306/furong_user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource